config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: {sign_in: :log_in, sign_out: :logout},
              controllers: { sessions: 'sessions' }

  resources :users do
    resources :feedbacks, only: %i[new create]
  end
  
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  resources :badges, only: :index

  namespace :admin do
    resources :badges
    resources :gists, shallow: true, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow:true, except: :index
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :title, :picture, presence: true

  enum rule: {
    tests_by_category: 0,
    on_the_first_attempt: 1,
    tests_by_level: 2
  }
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def show;end

  def edit;end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path,  notice: t('.success')
    else
      render :new
    end
  end

  def uodate
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private
  
  def badge_params
    params.require(:badge).permit(:title, :picture, :rule, :parameter)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end  
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @badges = current_user.badges
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle">
    <%= content_tag :span, badge.title, class: 'badge-title' %>
  </td>
  <td class="align-middle"><%=badge.picture%></td>
  <td class="align-middle"><%=badge.rule%></td>
  <td class="align-middle"><%= link_to t('.show'),admin_badge_path(badge)%>
  <td class="align-middle"><%= link_to t('.edit'), edit_admin_badge_path(badge)%></td>
  <td class="align-middle"><%= link_to t('.delete'),
                               admin_badge_path(badge),
                               data: {confirm: 'Are yuu sure?'},
                               method: :delete %>
  </td>
</tr>

app/views/admin/badges/_form_badge.html.erb
<%= form_with model: [:admin , @badge] do |form| %>
  <%= render 'shared/errors', resource: @badge%>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :badges_title%>
  </p>
  <p>
    <%= form.label :picture %><br>
    <%= form.text_field :picture, id: :badge_picture%>
  </p>
  <p>
    <%= form.label :rule %><br>
    <%= form.select :rule, Badge.rules.map{|k,_| [k.humanize, k]}, prompt: true, id: :badge_rule%>
  </p>
  <p>
    <%= form.label :parameter %><br>
    <%= form.text_field :parameter,id: :badge_parameter %>
  </p>
  <p><%= form.submit%></p>
<% end%>
<%= link_to t('.back'), admin_badges_path %>

app/views/admin/badges/create.html.erb
<h1>Admin::Badges#create</h1>
<p>Find me in app/views/admin/badges/create.html.erb</p>

app/views/admin/badges/edit.html.erb
<%= render 'form_badge'%>

app/views/admin/badges/index.html.erb
<div class="row mt-100%">
  <div class="col col-md-100%">
    <h1><%= t('.header') %></h1>
    <%= render 'shared/errors', resource: @badge%>
    <table class="table table-primary">
      <tr>
        <th class="sort-by-title pointer"><%= t('.title')%></th>
        <th><%= t('.picture')%></th>
        <th><%= t('.rule')%></th>
        <th colspan='3'><%= t('.action')%></th>
      </tr>
      <%= render @badges%>
    </table>
    <p><%= link_to t('.new_test'), new_admin_badge_path%></p>
    <p><%= link_to t('.new badge'), new_admin_badge_path%></p>
  </div>
</div>

app/views/admin/badges/new.html.erb
<%= render 'form_badge'%>

app/views/admin/badges/show.html.erb
<%= @badge.title %>

app/views/admin/badges/uodate.html.erb
<h1>Admin::Badges#uodate</h1>
<p>Find me in app/views/admin/badges/uodate.html.erb</p>