config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: {sign_in: :log_in, sign_out: :logout},
              controllers: { sessions: 'sessions' }

  resources :users do
    resources :feedbacks, only: %i[new create]
  end
  
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  resources :badges, only: :index

  namespace :admin do
    resources :badges
    resources :gists, shallow: true, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow:true, except: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < User
 
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_count_answers, on: :create

  scope :find_true_answer, -> {where(correct: true)}

  private

  def validate_count_answers
    errors.add(:base, 'Maximum answers must be 4') if question.answers.count > 3
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :title, :picture, presence: true

  enum rule: {
    tests_by_category: 0,
    on_the_first_attempt: 1,
    tests_by_level: 2
  }
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord

  has_many :tests, dependent: :destroy

  default_scope {order(title: :asc)}

  has_many :tests, dependent: :destroy

  validates :title, presence: true

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  
  validates :body, presence: true
end

app/models/result.rb
# frozen_string_literal: true

class Result < ApplicationRecord

  REFERENCE_POINT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def completed?
    current_question.nil? || time_left?
  end

  def time_left?
    Time.current - created_at > test.timer.minutes
  end

  def left_time
    return if self.test.timer.nil?

    test_time = (created_at + test.timer * 60) - Time.current
    test_time.positive? ? test_time.to_i : 0
  end

  def results_percent
    correct_questions.to_f * 100 / test.questions.size
  end

  def test_full_completed?
    results_percent >= REFERENCE_POINT
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  private

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.find_true_answer
  end

  def set_current_question
    self.current_question = next_question
  end

  def next_question
    if new_record?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'

  has_many :questions, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :users, through: :results, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, ggreater_than_or_equal_to: 0 }
  validates :timer, numericality: { only_integer: true, greater_than: 0 }

  scope :lite, -> {where(level: 0..1)}
  scope :medium, -> {where(level: 2..4)}
  scope :hard, -> {where(level: 5..Float::INFINITY)}

  scope :test_titles, ->(title){
    joins(:category)
      .where(categories: { title: title })
      .order(title: :desc)
  }

  def self.find_titles(title)
    test_titles(title).pluck(:title)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :results, dependent: :destroy
  has_many :tests , through: :results, dependent: :destroy
  has_many :author_tests, foreign_key: :author_id, class_name: 'Test', dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP },uniqueness: true

  def find_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    results.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  
  def create
    @result = Result.find(params[:result_id])
    gist_question = GistQuestionService.new.call(@result.current_question)

    if gist_question.success?
      Gist.create!(git_pull_url: gist_question.html_url,
                   question: @result.current_question,
                   user: current_user)
      flash[:notice] =  view_context.link_to(t('.success'), gist_question.html_url, target: '_blank')
    else
      flash[:allert] = t('.failure')
    end

    redirect_to @result
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  
  def current_year
    Time.current.year
  end

  def github_url(name,repo)
    link_to 'TestGuru', "https://github.com/#{name}/#{repo}",target: :_blank
  end

  def question_header(question)
    question.persisted? ? "#{t('.edit')} #{question.test.title} #{t('.question')} " : "#{t('.create_new')} #{t('.question')}  #{@test.title}"
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/admin/_nav.html.erb
<div class="nav nav-admin">
  <span class="nav-admin title"> TestGuru <%= t('.admin')%> <%= t('.panel') %></span>
  <div class="nav-admin user">
    <%= t('.welcome')%>, <b class="nav-admin user-email"><%= current_user.email%></b> Guru |
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav'%>
    <%= render 'shared/flash'%>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav'%>
    <div class="container">
      <%= render 'shared/flash'%>
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: {resource_id: resource.id} do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>
    </h2>
      <ul>
        <% resource.errors.full_messages.each do |message|%>
        <li> <%= message %> </li>
        <%end%>
      </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message|%>
  <div class='flash  alert <%= type %>'>
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">  
  <p> <%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'https://thinknetica.com/', target: :_blank %></p>
  <h5><p><%= t('.author') %> Vladimir Ostapenko repo: <%= github_url("Gluuck", "TestGuru") %></p></h5>

  <h5> <%= t('.year') %> <%= current_year%></h5>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <% if current_user.is_a?(Admin) %>
    <%= link_to 'TestGuru' , admin_tests_path, class: 'navbar-brand' %> | 
    <%= link_to 'Badges', admin_badges_path, class: 'navbar-brand' %>
  <% else %>
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
    <h6><%= link_to 'Badges', badges_path, class: 'navbar-brand' %></h6>
  <% end %>
  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.welcome') %> <b><%= current_user.first_name %></b> Guru |
      <%= link_to t('.log_out'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.registration'), new_user_registration_path%>
      <%= link_to t('.login'), new_user_session_path%>
    <% end %>
  </span>
</nav>