config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: {sign_in: :log_in, sign_out: :logout},
              controllers: { sessions: 'sessions' }

  resources :users do
    resources :feedbacks, only: %i[new create]
  end
  
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :results, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  resources :badges, only: :index

  namespace :admin do
    resources :badges
    resources :gists, shallow: true, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow:true, except: :index
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_count_answers, on: :create

  scope :find_true_answer, -> {where(correct: true)}

  private

  def validate_count_answers
    errors.add(:base, 'Maximum answers must be 4') if question.answers.count > 3
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  
  before_action :authenticate_user!
  before_action :find_question, only: %i[new create ]
  before_action :set_answer, only: %i[show edit update destroy]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body%>
  <%= link_to t('.show'), admin_answer_path(answer)%>
  <%= link_to t('.edit'), edit_admin_answer_path(answer)%>
  <%= link_to t('.delete'),
      admin_answer_path(answer),
      method: :delete,
      data: {confirm: 'Are yuu sure?'}%>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin,@question,@answer] do |form| %>
  <%= render 'shared/errors', resource: @answer%>
  <p>
    <%= form.label :body%>
    <%= form.text_area :body, id: :answer_body, rows:7, cols: 60%>
  </p>
  <p>
    <%= form.label :correct%>
    <%= form.check_box :correct, id: :answer_correct%>
  </p>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/answers/edit.html.erb
<h1><%= t('.editing_answer')%></h1>
<p>
  <h3><%= @answer.question.body%></h3>
</p>

<%= render 'form', answer: @answer %>

<%= link_to t('.back'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1><%= t('.new_answer') %></h1>
<p>
  <h3><%= @question.body%></h3>
</p>
<%= render 'form', answer: @answer %>

<%= link_to t('.back'), admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<p id="notice"><%= notice %></p>
<%= @answer.question.body%><br>
<p>
  <b><%= t('.answer')%>: </b>
  <%= @answer.body%>
</p>
<p>
  <b><%= t('.correct')%>: </b>
  <%= @answer.correct%>
</p>

<%= link_to t('.edit'), edit_admin_answer_path(@answer) %> |
<%= link_to t('.back'), admin_question_path(@answer.question) %>